import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grocery Express</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Grocery Express!</h1>
        <p className={styles.description}>Let's go shopping!</p>
        <div className={styles.register}>
          <form action="/send-data-here" method="post">
            <label for="first">Username:</label>
            <input type="text" id="userName" name="userName" />
            <label for="last">Password:</label>
            <input type="text" id="password" name="password" />
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
